### ISSUE TITLE
Need to set up Firebase Hosting on this project

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/Fairfield-Integrated-Systems-Calendar#1]
**( was told the issue may be resolved by uninstalling and reinstalling node.js on my computer )**

- Needs to be continually deployable from the IDE where the code is written (WebStorm IDE by JetBrains)
- Need to set up custom domain

See screenshots of Terminal errors below (not sure how to resolve):

<img width="1337" alt="Screen Shot 2022-11-28 at 9 15 06 AM" src="https://user-images.githubusercontent.com/89541068/204297706-10e5c69e-2780-4b4a-be38-6abeb1a5f72b.png">
<img width="1595" alt="Screen Shot 2022-11-28 at 9 15 12 AM" src="https://user-images.githubusercontent.com/89541068/204297720-3d6c2395-4ac0-4697-9606-70f7ba6062a2.png">
<img width="1463" alt="Screen Shot 2022-11-28 at 9 15 19 AM" src="https://user-images.githubusercontent.com/89541068/204297730-d56728ce-2703-40d3-8f20-c8f4e01c6047.png">
<img width="2035" alt="Screen Shot 2022-11-28 at 9 15 25 AM" src="https://user-images.githubusercontent.com/89541068/204297737-e4fd7838-4eef-46fb-9eeb-0f213f4476da.png">
<img width="1779" alt="Screen Shot 2022-11-28 at 9 15 31 AM" src="https://user-images.githubusercontent.com/89541068/204297742-e5bb968e-10d8-47aa-914e-af93acc3065c.png">
<img width="1416" alt="Screen Shot 2022-11-28 at 9 15 38 AM" src="https://user-images.githubusercontent.com/89541068/204297749-e55c1b87-f125-444b-af24-d54649bb2e9a.png">

**Comment by weevil111** [comment]
Hi, @JakeLabate. I came here from freelancer.com. Do you still need help with the setup or is it resolved?
