### ISSUE TITLE
Calendar improvements

### ISSUE THREAD

**Issue by weevil111** [JakeLabate/Fairfield-Integrated-Systems-Calendar#10]
- [ ] Color code cards under TODO
- [ ] Add the functionality of adding multiple cards in the placeholders
- [ ] Split the calendar tab into two tabs: Today and Upcoming.

**Comment by JakeLabate** [comment]
i will pick the colors, ignore the colors task

ignore the calendar display task

do the function of multiple people per 'to-do' and to make the event repeating
