### ISSUE TITLE
Create 'set' and 'delete' firebase functions

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/Fairfield-Integrated-Systems-Calendar#2]
This will be on the 'lists' (3rd) tab on the index.html file. The user needs to be able to 'create' or 'set' new team members and new vehicles, and create the 2 subfields that go along with it. The user also needs to be able to 'delete' not-needed team members and vehicles. This may be done via dragging the 'card' over the trash can in the bottom right of the 'lists' tab, but I suspect an easier way would be to have a small 'x' in the top-right corner of each card, that uses the confirm() function, asking the user if they are sure they want to delete this item.

These functions are found around line 250 of the script.js file
```js
// New Team Member
function newTeamMember() {
	console.log('Creating new team member...');
}

// New Vehicle
function newVehicle() {
	console.log('Creating new vehicle...');
}
```

**Comment by weevil111** [comment]
@JakeLabate We are moving forward with the X button on the top right corner of each card. Correct? For deleting Team Members.

**Comment by JakeLabate** [comment]
Yes plz! - How do I pull the finished code that you changed (adding the add/delete features) into my IDE (WebStorm) I want to be able to edit the full code. Normally I just push the code from my IDE to github, but show do I pull it in (the other way)?

**Comment by weevil111** [comment]
@JakeLabate Ok. I have done some code refactoring. That is:
I have create a separate function in script.js that will add a Team Member to the list (The alternative was to repeat the code again and again)

What you have to do is to Merge the Pull Request. Here's how:
1. Go to this link: https://github.com/JakeLabate/Fairfield-Integrated-Systems-Calendar/pull/5
2. Click on **Merge** Button at the bottom
3. Go to your IDE and click on Pull.

**Comment by JakeLabate** [comment]
Are either of these right? 
<img width="607" alt="Screen Shot 2022-11-30 at 7 09 25 PM" src="https://user-images.githubusercontent.com/89541068/204933626-3db5a576-3405-4b60-8167-057241952d22.png">

**Comment by weevil111** [comment]
@JakeLabate Do you have existing changes? Meaning, have you made any changes that you have not pushed?

**Comment by JakeLabate** [comment]
No I have not

**Comment by weevil111** [comment]
@JakeLabate Then select the First option (Merge)

**Comment by JakeLabate** [comment]
Great it worked; thanks.

**Comment by weevil111** [comment]
@JakeLabate Wonderful!
Let me know if you need anything other assistance. I'll be glad to help.

**Comment by JakeLabate** [comment]
> @JakeLabate Wonderful!
> 
> Let me know if you need anything other assistance. I'll be glad to help.

@weevil111 great. I can pay you just about as fast as you can solve these problems (about)... so... if you keep solving them... I can keep paying you...

**Comment by weevil111** [comment]
@JakeLabate Thanks. I pulled an all-nighter today because of our time difference. I might reply late tomorrow, so my apologies in advance. Rest assured, I am and will be working on the issues (I'll complete the delete Team Member one before sleeping).

I am assuming the next two issues will be: (in order of their priority)
1. Solving the drag-and-drop transferData mentioned in the other repo issue
2. Using that transferData in the Webhook newEvent();

Please let me know if you want to prioritise any other issue over them.

**Comment by JakeLabate** [comment]
> @JakeLabate Thanks. I pulled an all-nighter today because of our time difference. I might reply late tomorrow, so my apologies in advance. Rest assured, I am and will be working on the issues (I'll complete the delete Team Member one before sleeping).
> 
> 
> 
> I am assuming the next two issues will be: (in order of their priority)
> 
> 1. Solving the drag-and-drop transferData mentioned in the other repo issue
> 
> 2. Using that transferData in the Webhook newEvent();
> 
> 
> 
> Please let me know if you want to prioritise any other issue over them.

Yes that is it, thanks. Talk soon.

**Comment by weevil111** [comment]
Sure, Talk to you later

**Comment by weevil111** [comment]
@JakeLabate I have added the delete functionality and also fixed a design issue with the popup form. Please have a look at the same link that I gave (https://weevil111.github.io/Fairfield-Integrated-Systems-Calendar/)

**Comment by JakeLabate** [comment]
Yes it looks like the delete function works. @weevil111 

However,

I notices 2 additional issues:
1 - There is a random floating ';' on the main "today" page
2 - There is now no more padding between the top label and the details of the 'team member' as there was with the rest of the cards.

Can we also please add a confirm() option, so the 'click to delete' is not instant, but requires confirmation?

Can we revert these changes back to how they were? as well as adding 'add' and 'remove' functionality with the 'vehicles' as well? Today if possible. I am due to deliver this project to the client tonight/tomorrow, so If you have time today, I'd like to see it spent on the resolution of these final issues? Many thanks.

**Comment by weevil111** [comment]
@JakeLabate It's 10 PM here, so I can't give you promises. But sure, I can get started right away.
I have another question: Don't you have some other way of communication? I sometimes get notification very late from github, and communication over GitHub issue comment is difficult.
Do you have something along the lines of slack or discord, etc for your organisation?

**Comment by weevil111** [comment]
@JakeLabate You see what I mean? It has already been 1 hour but, I am still waiting for your confirmation (btw I have already started working). I have 2-3 questions that I have to ask. We need a professional communication channel. I'll create one if you want. The delay in back and forth is killing our efficiency (and we have a deadline to meet).

**Comment by JakeLabate** [comment]
> @JakeLabate You see what I mean? It has already been 1 hour but, I am still waiting for your confirmation (btw I have already started working). I have 2-3 questions that I have to ask. We need a professional communication channel. I'll create one if you want. The delay in back and forth is killing our efficiency (and we have a deadline to meet).

Pardon? If you think I can be called at your convenience, this is definitely not going to work.

Have you asked your question? Or just complained because they aren't answered?

**Comment by weevil111** [comment]
@JakeLabate Oh no. I am sorry. I am not demanding anything. What I mean to say is I have to ask 2-3 questions. This is just a miscommunication. I think conversion from my native language to english seems to be very direct.
 I apologies again

**Comment by JakeLabate** [comment]
> @JakeLabate Oh no. I am sorry. I am not demanding anything. What I mean to say is I have to ask 2-3 questions. This is just a miscommunication. I think conversion from my native language to english seems to be very direct.
> 
>  I apologies again

I still don't know what your questions are.

If you are not a viable now, then so be it, you are the controller of your time, not me.

Can you work tomorrow? (My night)?

I would like to deliver this project to the client Friday during the EST workday if possible

**Comment by weevil111** [comment]
@JakeLabate I am already working. And I have not asked the questions. I am about to ask. 
I am available. I have to clear some things that's all.
I am sorry that I offended you @JakeLabate.
